# Generated by Django 4.0.4 on 2022-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_persona_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
